const CATEGORY = {
  GROCERIES: "Groceries",
  INSURANCE: "Insurance",
  INVESTMENT: "Investment",
  EATING_OUT: "Eating Out",
  MEDICINES: "Medicines",
  SHOPPING: "Shopping",
  INCOMING: "Incoming",
  CASHED_OUT: "Cashed Out",
  UNCATEGORISED: "Uncategorised",
  TRAVEL: "Travel",
  HOSPITAL: "Hospital",
  LENDING: "Lending",
  MISCELLANEOUS: "Miscellaneous",
  NOT_FOUND: "Not Found"
};

const insightsObj = {
  [CATEGORY.GROCERIES]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffcd6688",
    Reciepients: [
      "REKHA  DEVI",
      "OMM SAI STORE",
      "Q577113263",
      "ARATI  SWAIN",
      "SARASWATI  SINGH",
      "Q681773532",
      "BHARATPE90725319",
      "MAHABIR",
      "RAJIV  VISHWAKARMA",
      "7978332255",
      "Q762897006",
      "MANOJ KUMAR NAYAK",
      "AUTO FEED",
      "52491067@",
      "AUTO FEED",
      "52491067@",
      "Q262149230@",
      "Q65553382",
      "MUKESH KUMAR SAHU",
    ],
  },
  [CATEGORY.INSURANCE]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffa076f9",
    Reciepients: ["LIC", "BILLDESKTEZ"],
  },
  [CATEGORY.INVESTMENT]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ff7a9d54",
    Reciepients: [],
  },
  [CATEGORY.EATING_OUT]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "fff4d160",
    Reciepients: [
      "NEW KONARK",
      "74132382",
      "CELEBRATIONS",
      "Q43693152",
      "NAIK FAST FOOD",
      "DEVANSH ORBIT",
      "Q577289615",
      "MANOJ KUMAR BISWAL",
      "MANOJ KUMAR  BISWAL",
      "Q21565147",
      "DOMINOS",
      "TFS 90190007",
      "SURYAKANTA PAL",
      "SURYAKANTA  BEHERA",
      "FAZLUR RAHEMAN",
      "RAJASHREE SWAIN",
      "Q750847649",
      "KASINATH  PRADHAN",
      "Q755931683",
      "RANUBALA KAHNAR",
      "RANUBALA KANHAR",
      "Q994003801",
      "SALES CORPORATION",
      "SHALIMAR",
      "NARENDRA DAS",
      "HARINARAYAN GIRI",
      "Q823309834",
      "Q923616094",
      "JAGABALIA",
      "ZOMATO",
      "BIKTANT TEA SHOP",
      "GPAY-1121390",
      "FORUM GALERIA",
    ],
  },
  [CATEGORY.MEDICINES]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "fff3aa60",
    Reciepients: [
      "APOLLO PHARMACY",
      "SURUCHI MEDICINES",
      "SANJAY  SINGH",
      "SS6704301",
    ],
  },
  [CATEGORY.SHOPPING]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ff4a55a2",
    Reciepients: [],
  },
  [CATEGORY.INCOMING]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffff90bb",
    Reciepients: [],
  },
  [CATEGORY.CASHED_OUT]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffe7cea6",
    Reciepients: ["7077833588", "KUNTALA"],
  },
  [CATEGORY.UNCATEGORISED]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "176B87",
    Reciepients: [
      "AHEL HBP BHUBANESHWAR",
      "JOGENDRA NAHAK",
      "79785642812",
      "FETCOL",
      "BIKASH STORE",
      "11174785585",
      "PRADEP SAHU",
      "RAMAKANTA LENKA",
      "70935924",
      "BHARATPE907254",
      "75392983@",
      "JAI SHRI AGRO",
      "9437040855@",
      "STATIONARY",
      "9437980812",
    ],
  },
  [CATEGORY.TRAVEL]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ff84a7a1",
    Reciepients: [
      "ALLIANCE AIR",
      "OLACABS",
      "IXIGO",
      "9237978576",
      "STAR FUELS",
      "67172121",
      "BHAGABATI FILLING",
      "IRCTC"
    ],
  },
  [CATEGORY.HOSPITAL]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffaee2ff",
    Reciepients: ["APOLLO HOSPITALS"],
  },
  [CATEGORY.LENDING]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ff606c5d",
    Reciepients: ["7504850485", "00490100015654", "DEBASHISH BARIK"],
  },
  [CATEGORY.MISCELLANEOUS]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ffea906c",
    Reciepients: [
      "RELIANCE JIO",
      "SERVICEMARINES",
      "DTDC EXPRESS",
      "GOOGLE PLAY/PLAYSTORE",
      "BBPSBP",
      "YESB0YBLUP",
    ],
  },
  [CATEGORY.NOT_FOUND]: {
    Amount: 0,
    "Number of Transactions": 0,
    Color: "ff00dfa2",
    Reciepients: [
    ],

  }
};

module.exports = {
  CATEGORY,
  insightsObj,
};
